/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MultiSig } from "./MultiSig";
export * as factories from "./factories";
export { MultiSig__factory } from "./factories/MultiSig__factory";
